# Generated by Django 5.2.4 on 2025-07-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hruser",
            options={"verbose_name": "HR User", "verbose_name_plural": "HR Users"},
        ),
        migrations.AlterModelTable(
            name="hruser",
            table="hr_user",
        ),
    ]
