# Generated by Django 5.2.4 on 2025-07-18 21:39

import libs.customfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_user", "0002_alter_hruser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hruser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="hruser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="hruser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="hruser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="hruser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="hruser",
            name="username",
        ),
        migrations.AddField(
            model_name="hruser",
            name="name",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hruser",
            name="email",
            field=libs.customfields.EmailField(
                error_messages={"unique": "The username or password you entered is incorrect."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="hruser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hruser",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
