# Generated by Django 5.2.4 on 2025-07-19 19:10

import libs.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=libs.customfields.EmailField(max_length=254, unique=True),
        ),
    ]
