# Generated by Django 5.2.4 on 2025-07-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="recruiter",
            new_name="hr_user",
        ),
    ]
