# Generated by Django 5.2.4 on 2025-07-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_alter_candidate_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"verbose_name": "Candidate", "verbose_name_plural": "Candidates"},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name": "Education", "verbose_name_plural": "Educations"},
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
            },
        ),
        migrations.AlterModelTable(
            name="candidate",
            table="candidate",
        ),
        migrations.AlterModelTable(
            name="education",
            table="education",
        ),
        migrations.AlterModelTable(
            name="workexperience",
            table="work_experience",
        ),
    ]
