# Generated by Django 5.2.4 on 2025-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_alter_candidate_options_alter_education_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="tech_stack",
            field=models.TextField(
                blank=True,
                help_text="List of the technologies stack, separated by comma e.g Python, Django, PostgreSQL",
            ),
        ),
    ]
