# Generated by Django 5.2.4 on 2025-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0004_workexperience_tech_stack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="last_name",
        ),
        migrations.AddField(
            model_name="candidate",
            name="name",
            field=models.CharField(
                db_index=True,
                default=1,
                max_length=100,
                verbose_name="name and surname",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="school",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="company",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
