# Generated by Django 5.2.4 on 2025-07-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="created_at",
        ),
    ]
