# Generated by Django 5.2.4 on 2025-07-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_alter_candidate_email"),
        ("flow", "0002_initial"),
        ("job_posting", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidateflow",
            unique_together={("job_posting", "candidate")},
        ),
    ]
