# Generated by Django 5.2.4 on 2025-07-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="candidateflow",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="candidateflow",
            name="updated_at",
        ),
    ]
