# Generated by Django 5.2.4 on 2025-07-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateflow",
            name="activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_flows",
                to="flow.activity",
            ),
            preserve_default=False,
        ),
    ]
