# Generated by Django 5.2.4 on 2025-07-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0003_alter_candidateflow_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "Activity", "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="candidateflow",
            options={
                "verbose_name": "Candidate Flow",
                "verbose_name_plural": "Candidate Flows",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Statuses"},
        ),
        migrations.AlterModelTable(
            name="activity",
            table="activity",
        ),
        migrations.AlterModelTable(
            name="candidateflow",
            table="candidate_flow",
        ),
        migrations.AlterModelTable(
            name="status",
            table="status",
        ),
    ]
