# Generated by Django 5.2.4 on 2025-07-19 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0004_alter_activity_options_alter_candidateflow_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="activity_type",
        ),
        migrations.AddField(
            model_name="activity",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CandidateActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_activities_log",
                        to="flow.activity",
                    ),
                ),
                (
                    "candidate_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_activities_log",
                        to="flow.candidateflow",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_activities_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_activities_log",
                        to="flow.status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
