# Generated by Django 5.2.4 on 2025-07-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_remove_activity_activity_type_activity_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidateactivitylog",
            options={
                "verbose_name": "Candidate Activity Log",
                "verbose_name_plural": "Candidate Activity Logs",
            },
        ),
        migrations.AlterModelTable(
            name="candidateactivitylog",
            table="candidate_activity_log",
        ),
    ]
