# Generated by Django 5.2.4 on 2025-07-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_alter_candidateactivitylog_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="hr_user",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="candidateactivitylog",
            old_name="activity_type",
            new_name="activity",
        ),
        migrations.RenameField(
            model_name="candidateactivitylog",
            old_name="status_type",
            new_name="status",
        ),
    ]
