# Generated by Django 5.2.4 on 2025-07-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0007_rename_hr_user_activity_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="description",
            new_name="note",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="candidate_flow",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="status",
        ),
    ]
