# Generated by Django 5.2.4 on 2025-07-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0008_rename_description_status_note_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateactivitylog",
            name="status",
        ),
    ]
