# Generated by Django 5.2.4 on 2025-07-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0009_remove_candidateactivitylog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateactivitylog",
            name="created_by",
        ),
    ]
