# Generated by Django 5.2.4 on 2025-07-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientcompany",
            options={
                "verbose_name": "Client Company",
                "verbose_name_plural": "Client Companies",
            },
        ),
        migrations.AlterModelTable(
            name="clientcompany",
            table="client_company",
        ),
    ]
