# Generated by Django 5.2.4 on 2025-07-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
            },
        ),
        migrations.AlterModelTable(
            name="jobposting",
            table="job_posting",
        ),
    ]
